#!/bin/bash
sleep 30
source /etc/environment
REPOS=/opt/phacility/git/
GIT=/opt/cgit/
CGIT=${GIT}active
DEPR=${GIT}deprecated

res=$(curl -s $PHAB_HOST/api/diffusion.repository.search -d api.token=$PHAB_TOKEN -d queryKey=active)
_py="
import sys
import json

obj = json.loads(sys.stdin.read())
results = []
for j in obj['result']['data']:
    results.append(j['fields']['callsign'] + '.' + str(j['id']))

for i in sorted(results):
    print(i)
"

for item in $(echo $res | python -c "$_py"); do
    call=$(echo $item | cut -d "." -f 1)
    num=$(echo $item | cut -d "." -f 2)
    _page="$_page
"$(echo "| r$call | [download](/zip/$num) |")
    linked=$CGIT/$call
    if [ ! -e $linked ]; then
        if [ ! -e "$DEPR/$call" ]; then
            echo "r$call" > $REPOS$num/description
            ln -s $REPOS/$num $linked
        fi
    fi
done
