#!/bin/bash
source /etc/environment
REPOS=/opt/phacility/git/
_page='
> **Downloading these bundles uses bandwidth and some of them are large!!!**
> this page is edited by a bot
> do _NOT_ edit it here

These are origin repositories, you must hit download and...
```
mkdir repo
mv {repo}.zip repo/
cd repo
unzip {repo}.zip
cd ..
git clone repo workingdir
```

| name | link |
| ---- | ---- |'

res=$(curl -s $PHAB_HOST/api/diffusion.repository.search -d api.token=$PHAB_TOKEN -d queryKey=active)
_py="
import sys
import json

obj = json.loads(sys.stdin.read())
results = []
for j in obj['result']['data']:
    results.append(j['fields']['callsign'] + '.' + str(j['id']))

for i in sorted(results):
    print(i)
"

has=0
for item in $(echo $res | python -c "$_py"); do
    has=1
    call=$(echo $item | cut -d "." -f 1)
    num=$(echo $item | cut -d "." -f 2)
    _page="$_page
"$(echo "| r$call | [download](/zip/$num) |")
    echo "r$call" > $REPOS$num/description
done

if [ $has -eq 0 ]; then
    echo "no repositories found"
    exit 1
fi

last=/tmp/repos.content
new=$(echo "$_page" | sha256sum | cut -d " " -f 1)
skip=0
if [ -e $last ]; then
    chk=$(cat $last)
    if [[ "$chk" == "$new" ]]; then
        skip=1
    fi
fi
echo "$new" > $last

if [ $skip -eq 1 ]; then
    echo "no change"
    exit
fi

content=$(echo "$_page" | python -c "import sys, urllib.parse; print(urllib.parse.quote(sys.stdin.read()))")
curl -s $PHAB_HOST/api/phriction.edit \
    -d api.token=$PHAB_TOKEN \
    -d slug="meta/phab/repos/" \
    -d title="Repos" \
    -d content=$content >/dev/null
