#!/bin/bash
source /etc/environment
COMMON=$PHAB_INBOX
HEADER="> this page is generated by a bot
> **DO NOT** edit it here
"

for f in $(find $COMMON -type f -name "*\.md"); do
	name=$(basename $f | sed "s/\.md$//g")
	title="$(tr '[:lower:]' '[:upper:]' <<< ${name:0:1})${name:1}"
	echo "loading: $f ($name $title)"
	content="$HEADER"$(cat $f)
	content=$(echo "$content" | python -c "import sys, urllib.parse; print(urllib.parse.quote(sys.stdin.read()))")
	curl -s $PHAB_HOST/api/phriction.edit \
		-d api.token=$PHAB_TOKEN \
		-d slug=meta/reports/$name \
		-d title=$title \
		-d content=$content > /dev/null
	if [ $? -ne 0 ]; then
		echo "report upload error: $name"
	fi
	rm -f $f
done

