/**
 * Copyright 2018
 * MIT License
 * Phabricator specific handling
 */
module common;
import phabricator.api;
import phabricator.common;
import phabricator.util.conv2wiki;
import phabricator.util.diffusion;
import phabricator.util.indexing;
import phabricator.util.projects;
import phabricator.util.tasks;
import phabricator.util.wiki2dash;
import std.algorithm: canFind, sort;
import std.ascii: isDigit, isPunctuation, isWhite;
import std.conv: to;
import std.datetime;
import std.getopt;
import std.json;
import std.random;
import std.string: endsWith, format, join, split, startsWith, strip, toLower;
import std.typecons;
import std.getopt;

// generic page header
private enum GenPageHeader = "
> this page is generated by a bot
> **DO NOT** edit it here
\n";

// NOTE: relic of coming from matrix-bot
private enum SynapseLine = "SYNAPSE_";

// Phabricator items
private enum PhabIndicator = SynapseLine ~ "PHAB_";

// URL for phab
private enum PhabricatorURL = PhabIndicator ~ "URL";

// phabricator api token
private enum PhabricatorToken = PhabIndicator ~ "TOKEN";

// dashboard (to update, wiki phid)
public enum DashOpts = PhabIndicator ~ "TO_DASH";

// Unmodified tasks (project, months, room)
public enum UnmodifiedOpts = PhabIndicator ~ "UNMODIFIED";

// index settings (slug, title)
public enum IndexOpts = PhabIndicator ~ "INDEX";

// contact settings (slug, title, path, callsign)
public enum ContactsOpts = PhabIndicator ~ "CONTACTS";

// whois settings (slug, title, path, callsign)
public enum WhoIsOpts = PhabIndicator ~ "WHOIS";

// Synapse lookup resolution (Paste PHID)
public enum LookupsPHID = "LOOKUP_PHID";

// User PHID
public enum PhabricatorUser = PhabIndicator ~ "USER_PHID";

// hidden tasks (paste phid, room)
public enum HiddenOpts = PhabIndicator ~ "HIDDEN";

public class API
{
    @property public string[string] context;
}

/**
 * Get settings
 */
public static Settings getSettings(API api)
{
    auto settings = Settings();
    settings.url = api.context[PhabricatorURL];
    settings.token = api.context[PhabricatorToken];
    return settings;
}

public static void onError(string message)
{
}

/**
 * Perform setup
 */
API setup(string[] args)
{
    string env;
    auto opts = getopt(args,
                       std.getopt.config.required,
                       "env",
                       &env);

    auto api = new API();
    loadEnvironmentFile(api.context, env, SynapseLine);
    return api;
}
