/**
 * Copyright 2018
 * MIT License
 * Phabricator specific handling
 */
module projects;
import phabricator.api;
import phabricator.common;
import phabricator.util.conv2wiki;
import phabricator.util.diffusion;
import phabricator.util.indexing;
import phabricator.util.projects;
import phabricator.util.tasks;
import phabricator.util.wiki2dash;
import std.algorithm: canFind, sort;
import std.ascii: isDigit, isPunctuation, isWhite;
import std.conv: to;
import std.datetime;
import std.getopt;
import std.json;
import std.random;
import std.string: endsWith, format, join, split, startsWith, strip, toLower;
import std.typecons;

// generic page header
private enum GenPageHeader = "
> this page is generated by a bot
> **DO NOT** edit it here
\n";

private enum PhabIndicator = "PHAB_";

// phabricator api token
private enum PhabricatorToken = PhabIndicator ~ "TOKEN";

// dashboard (to update, wiki phid)
private enum DashOpts = PhabIndicator ~ "TO_DASH";

// Unmodified tasks (project, months, room)
private enum UnmodifiedOpts = PhabIndicator ~ "UNMODIFIED";

// index settings (slug, title)
private enum IndexOpts = PhabIndicator ~ "INDEX";

// contact settings (slug, title, path, callsign)
private enum ContactsOpts = PhabIndicator ~ "CONTACTS";

// whois settings (slug, title, path, callsign)
private enum WhoIsOpts = PhabIndicator ~ "WHOIS";

// Synapse lookup resolution (Paste PHID)
private enum LookupsPHID = "LOOKUP_PHID";

// User PHID
private enum PhabricatorUser = PhabIndicator ~ "USER_PHID";

// hidden tasks (paste phid, room)
private enum HiddenOpts = PhabIndicator ~ "HIDDEN";

/**
 * Join projects
 */
public static bool doJoinProjects(MatrixAPI api)
{
    try
    {
        auto settings = getSettings(api);
        auto user = api.context[PhabricatorUser];
        auto proj = construct!ProjectAPI(settings);
        auto membership = proj.membersActive()[ResultKey][DataKey];
        string[] results;
        foreach (project; membership.array)
        {
            auto members = project["attachments"]["members"]["members"].array;
            auto matched = false;
            foreach (member; members)
            {
                auto phid = member["phid"].str;
                if (phid == user)
                {
                    matched = true;
                    break;
                }
            }

            if (!matched)
            {
                results ~= project[FieldsKey]["name"].str;
            }
        }

        if (results.length > 0)
        {
            api.sendText(api.context[DebugRoom],
                         "not a member of these projects:\n" ~
                         join(results, "\n"));
            return assignToActive(getSettings(api), user);
        }
        else
        {
            return true;
        }
    }
    catch (Exception e)
    {
        return false;
    }
}
